version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.6-browsers
        environment:
          DATABASE_URL: postgres://postgres@localhost/circle_test
      - image: circleci/postgres:9.6.5-alpine-ram
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
